apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: shelter-data
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      external:
        type: nodeport
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
