apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: amq-streams
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      external:
        type: route
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
