# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'ruby-kafka'
gem 'faker'
gem 'croupier', '~> 2.0.0.rc2'
gem 'slosilo'
gem 'conjur-api'
